export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  PUMP_IN_MAINTENANCE: "PUMP_IN_MAINTENANCE",
  PUMP_NO_AVAILABLE: "PUMP_NO_AVAILABLE",
  PUMP_ROTATE_FIRST: "PUMP_ROTATE_FIRST",
  PUMP_SUPPLY_RISK_CONFIRM: "PUMP_SUPPLY_RISK_CONFIRM"
} as const;
