ERROR_CODES = {
  "AUTH_REQUIRED": "AUTH_REQUIRED",
  "RBAC_DENIED": "RBAC_DENIED",
  "VALIDATION_FAILED": "VALIDATION_FAILED",
  "PUMP_TARGET_UNDER_REPAIR": "PUMP_TARGET_UNDER_REPAIR",
  "PUMP_NO_AVAILABLE_STANDBY": "PUMP_NO_AVAILABLE_STANDBY",
  "PUMP_SUPPLY_AT_RISK": "PUMP_SUPPLY_AT_RISK",
}
